/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 *
 * @author Jhumari Soto
 */
public class frmSistemaVeterinaria extends javax.swing.JFrame {

    /**
     * Creates new form frmSistemaVeterinaria
     */
    
     public frmSistemaVeterinaria() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Proyecto Final");
         setIconImage(new ImageIcon(getClass().getResource("/Imagenes/HISTORIALMEDICO.jpg")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/Imagenes/FONDO.jpg"));
        JLabel fondo= new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
        
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        Insertar = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        InsertarAnimal = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        ConsultarAnimal = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        InsertarCita = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setRequestFocusEnabled(false);

        fileMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\Cliente.png")); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("CLIENTE");

        Insertar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\user-.png")); // NOI18N
        Insertar.setMnemonic('o');
        Insertar.setText("Insertar Cliente   ");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        fileMenu.add(Insertar);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Eliminar Cliente ");
        fileMenu.add(saveMenuItem);

        Consultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\Help.png")); // NOI18N
        Consultar.setMnemonic('a');
        Consultar.setText("Consultar Cliente ");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        fileMenu.add(Consultar);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\PERSONA.jpg")); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("PERSONA");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Insertar Persona ");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Eliminar Persona  ");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Consultar Persona  ");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\ANIMALES.gif")); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("ANIMALES");

        InsertarAnimal.setMnemonic('c');
        InsertarAnimal.setText("Insertar Animal ");
        InsertarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarAnimalActionPerformed(evt);
            }
        });
        helpMenu.add(InsertarAnimal);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Eliminar Animal ");
        helpMenu.add(aboutMenuItem);

        ConsultarAnimal.setText("Consultar Animal ");
        ConsultarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarAnimalActionPerformed(evt);
            }
        });
        helpMenu.add(ConsultarAnimal);

        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\CITAS.jpg")); // NOI18N
        jMenu1.setText("CITAS");

        InsertarCita.setText("Insertar Citas");
        InsertarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarCitaActionPerformed(evt);
            }
        });
        jMenu1.add(InsertarCita);

        jMenuItem3.setText("Actualizar Citas");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Consultar Citas");
        jMenu1.add(jMenuItem4);

        menuBar.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\FECHAVACUNACION.gif")); // NOI18N
        jMenu2.setText("FECHA/VACUNACION");

        jMenuItem5.setText("Insertar Fecha de  Vacunacion");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Consultar Fecha de Vacunacion");
        jMenu2.add(jMenuItem6);

        menuBar.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhumari Soto\\Desktop\\HISTORIALMEDICO.jpg")); // NOI18N
        jMenu3.setText("HISTORIAL MÉDICO");

        jMenuItem7.setText("Insertar Historial Medico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Consultar Historial Medico");
        jMenu3.add(jMenuItem8);

        menuBar.add(jMenu3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(605, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 379, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasteMenuItemActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        // TODO add your handling code here:
        
         frmCliente C = new frmCliente(); 
        C.setVisible(true);
        dispose();    
                             
    }//GEN-LAST:event_InsertarActionPerformed

    private void ConsultarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarAnimalActionPerformed
          
         frmConsultarAnimal CA= new frmConsultarAnimal();
         CA.setVisible(true);
         dispose();
    }//GEN-LAST:event_ConsultarAnimalActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
       frmConsultarCliente Cc = new frmConsultarCliente();
     Cc.setVisible(true);
            dispose();
                           
    }//GEN-LAST:event_ConsultarActionPerformed

    private void InsertarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarAnimalActionPerformed
       
        frmMascotas M = new frmMascotas(); 
        M.setVisible(true);
        dispose();    
      
    }//GEN-LAST:event_InsertarAnimalActionPerformed

    private void InsertarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarCitaActionPerformed
        
        frmCitas C = new frmCitas(); 
        C.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_InsertarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSistemaVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSistemaVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSistemaVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSistemaVeterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSistemaVeterinaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Consultar;
    private javax.swing.JMenuItem ConsultarAnimal;
    private javax.swing.JMenuItem Insertar;
    private javax.swing.JMenuItem InsertarAnimal;
    private javax.swing.JMenuItem InsertarCita;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
